apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: petclinic-services
  namespace: monitoring
spec:
  # Watch Services in the petclinic namespace
  namespaceSelector:
    matchNames:
      - petclinic
  # Target all Services deployed by our Helm chart
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: Helm
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
