apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "petclinic-service.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "petclinic-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "petclinic-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "petclinic-service.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      securityContext:
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
      containers:
        - name: {{ include "petclinic-service.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
              protocol: TCP
          env:
            - name: JAVA_OPTS
              value: "-XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/./urandom"
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            {{- if eq .Values.probeType "tcp" }}
            tcpSocket:
              port: {{ .Values.probePort | default .Values.containerPort }}
            {{- else }}
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.probePort | default .Values.containerPort }}
            {{- end }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          livenessProbe:
            {{- if eq .Values.probeType "tcp" }}
            tcpSocket:
              port: {{ .Values.probePort | default .Values.containerPort }}
            {{- else }}
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.probePort | default .Values.containerPort }}
            {{- end }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          securityContext:
            allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
