image:
  repository: 703671902584.dkr.ecr.us-east-1.amazonaws.com/petclinic/admin-server
  tag: fbfa75a3be735873d0e447334b225756a8678ae4
containerPort: 9090
service:
  port: 9090
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 300m
    memory: 512Mi
env:
  - name: SPRING_PROFILES_ACTIVE
    value: "kubernetes"
  - name: CONFIG_SERVER_URL
    value: "http://config-server:8888"
