image:
  repository: 703671902584.dkr.ecr.us-east-1.amazonaws.com/petclinic/admin-server
  tag: 9e4b2a59298f0356260745d2c7b85c36e5a5ffbf
containerPort: 9090
service:
  port: 9090
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 300m
    memory: 512Mi
env:
  - name: SPRING_PROFILES_ACTIVE
    value: "kubernetes"
  - name: CONFIG_SERVER_URL
    value: "http://config-server:8888"
