image:
  repository: 703671902584.dkr.ecr.us-east-1.amazonaws.com/petclinic/admin-server
  tag: fe3b3c0f9a02ef716ebdd413d41e75f44a1d0157
containerPort: 9090
service:
  port: 9090
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 300m
    memory: 512Mi
env:
  - name: SPRING_PROFILES_ACTIVE
    value: "kubernetes"
  - name: CONFIG_SERVER_URL
    value: "http://config-server:8888"
