image:
  repository: 703671902584.dkr.ecr.us-east-1.amazonaws.com/petclinic/api-gateway
  tag: 0cf4f70414279f20ca2e23c820b7b67bb32b18e5
containerPort: 8080
# ClusterIP — the Ingress (ALB) handles all external traffic
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
  # host: app.yourdomain.com  # uncomment and set in Phase 7 when domain is ready
  host: ""
env:
  - name: SPRING_PROFILES_ACTIVE
    value: "kubernetes"
  - name: CONFIG_SERVER_URL
    value: "http://config-server:8888"
  - name: SPRING_APPLICATION_JSON
    value: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://discovery-server:8761/eureka/"}}}}'
