image:
  repository: 703671902584.dkr.ecr.us-east-1.amazonaws.com/petclinic/api-gateway
  tag: 13d12ceeb21f8e7824ffc8c6728d7189fcd08575
containerPort: 8080
# ClusterIP — the Ingress (ALB) handles all external traffic
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
  # host: app.yourdomain.com  # uncomment and set in Phase 7 when domain is ready
  host: ""
env:
  - name: SPRING_PROFILES_ACTIVE
    value: "kubernetes"
  - name: CONFIG_SERVER_URL
    value: "http://config-server:8888"
