image:
  repository: 703671902584.dkr.ecr.us-east-1.amazonaws.com/petclinic/customers-service
  tag: 13d12ceeb21f8e7824ffc8c6728d7189fcd08575
containerPort: 8081
service:
  port: 8081
env:
  - name: SPRING_PROFILES_ACTIVE
    value: "kubernetes"
  - name: CONFIG_SERVER_URL
    value: "http://config-server:8888"
  - name: SERVER_PORT
    value: "8081"
  - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
    value: "http://discovery-server:8761/eureka/"
