image:
  repository: 703671902584.dkr.ecr.us-east-1.amazonaws.com/petclinic/customers-service
  tag: 0cf4f70414279f20ca2e23c820b7b67bb32b18e5
containerPort: 8081
service:
  port: 8081
env:
  - name: SPRING_PROFILES_ACTIVE
    value: "kubernetes"
  - name: CONFIG_SERVER_URL
    value: "http://config-server:8888"
  - name: SERVER_PORT
    value: "8081"
  - name: SPRING_APPLICATION_JSON
    value: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://discovery-server:8761/eureka/"}}}}'
