image:
  repository: 703671902584.dkr.ecr.us-east-1.amazonaws.com/petclinic/discovery-server
  tag: 2fe9d5b7e6340ac177a7459f0d12d3beaf6f9f0d
containerPort: 8761
service:
  port: 8761
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 300m
    memory: 512Mi
env:
  - name: SPRING_PROFILES_ACTIVE
    value: "kubernetes"
  - name: CONFIG_SERVER_URL
    value: "http://config-server:8888"
