image:
  repository: 703671902584.dkr.ecr.us-east-1.amazonaws.com/petclinic/vets-service
  tag: 2fe9d5b7e6340ac177a7459f0d12d3beaf6f9f0d
containerPort: 8083
service:
  port: 8083
env:
  - name: SPRING_PROFILES_ACTIVE
    value: "kubernetes"
  - name: CONFIG_SERVER_URL
    value: "http://config-server:8888"
  - name: SERVER_PORT
    value: "8083"
  - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
    value: "http://discovery-server:8761/eureka/"
