image:
  repository: 703671902584.dkr.ecr.us-east-1.amazonaws.com/petclinic/vets-service
  tag: 944aba2c79b085057801a9db733009303531d357
containerPort: 8083
service:
  port: 8083
env:
  - name: SPRING_PROFILES_ACTIVE
    value: "kubernetes"
  - name: CONFIG_SERVER_URL
    value: "http://config-server:8888"
  - name: SERVER_PORT
    value: "8083"
  - name: SPRING_APPLICATION_JSON
    value: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://discovery-server:8761/eureka/"}}}}'
