image:
  repository: 703671902584.dkr.ecr.us-east-1.amazonaws.com/petclinic/visits-service
  tag: fe3b3c0f9a02ef716ebdd413d41e75f44a1d0157
containerPort: 8082
service:
  port: 8082
env:
  - name: SPRING_PROFILES_ACTIVE
    value: "kubernetes"
  - name: CONFIG_SERVER_URL
    value: "http://config-server:8888"
  - name: SERVER_PORT
    value: "8082"
  - name: SPRING_APPLICATION_JSON
    value: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://discovery-server:8761/eureka/"}}}}'
