image:
  repository: 703671902584.dkr.ecr.us-east-1.amazonaws.com/petclinic/visits-service
  tag: f69d2c9638cb5e2baf5a313021079f79275b80dd
containerPort: 8082
service:
  port: 8082
env:
  - name: SPRING_PROFILES_ACTIVE
    value: "kubernetes"
  - name: CONFIG_SERVER_URL
    value: "http://config-server:8888"
  - name: SERVER_PORT
    value: "8082"
  - name: SPRING_APPLICATION_JSON
    value: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://discovery-server:8761/eureka/"}}}}'
